/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.jSchema.Array;
import org.xtext.example.mydsl.jSchema.Includes;
import org.xtext.example.mydsl.jSchema.JSchemaPackage;
import org.xtext.example.mydsl.jSchema.PrimitiveObject;
import org.xtext.example.mydsl.jSchema.PrimitiveProperties;
import org.xtext.example.mydsl.jSchema.Property;
import org.xtext.example.mydsl.jSchema.STRING;
import org.xtext.example.mydsl.jSchema.Types;
import org.xtext.example.mydsl.jSchema.hasProperties;
import org.xtext.example.mydsl.services.JSchemaGrammarAccess;

@SuppressWarnings("all")
public class JSchemaSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private JSchemaGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == JSchemaPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case JSchemaPackage.ARRAY:
				if (rule == grammarAccess.getArrayRule()) {
					sequence_Array(context, (Array) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getTypesRule()) {
					sequence_Types(context, (Array) semanticObject); 
					return; 
				}
				else break;
			case JSchemaPackage.INCLUDES:
				sequence_Includes(context, (Includes) semanticObject); 
				return; 
			case JSchemaPackage.NUMBER:
				sequence_Number(context, (org.xtext.example.mydsl.jSchema.Number) semanticObject); 
				return; 
			case JSchemaPackage.OBJECT:
				sequence_Object(context, (org.xtext.example.mydsl.jSchema.Object) semanticObject); 
				return; 
			case JSchemaPackage.PRIMITIVE_OBJECT:
				sequence_PrimitiveObject(context, (PrimitiveObject) semanticObject); 
				return; 
			case JSchemaPackage.PRIMITIVE_PROPERTIES:
				sequence_PrimitiveProperties(context, (PrimitiveProperties) semanticObject); 
				return; 
			case JSchemaPackage.PROPERTY:
				sequence_Property(context, (Property) semanticObject); 
				return; 
			case JSchemaPackage.STRING:
				sequence_Types(context, (STRING) semanticObject); 
				return; 
			case JSchemaPackage.TYPES:
				sequence_Types(context, (Types) semanticObject); 
				return; 
			case JSchemaPackage.HAS_PROPERTIES:
				sequence_hasProperties(context, (hasProperties) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Array returns Array
	 *
	 * Constraint:
	 *     (name=ID (properties+=Property properties+=Property*)?)
	 */
	protected void sequence_Array(ISerializationContext context, Array semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Includes returns Includes
	 *
	 * Constraint:
	 *     (objectID+=STRING objectID+=STRING*)
	 */
	protected void sequence_Includes(ISerializationContext context, Includes semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Number returns Number
	 *
	 * Constraint:
	 *     (number=INT decimal=INT?)
	 */
	protected void sequence_Number(ISerializationContext context, org.xtext.example.mydsl.jSchema.Number semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Object
	 *     Object returns Object
	 *
	 * Constraint:
	 *     (name=ID includeObjects=Includes? properties=hasProperties?)
	 */
	protected void sequence_Object(ISerializationContext context, org.xtext.example.mydsl.jSchema.Object semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns PrimitiveObject
	 *     PrimitiveObject returns PrimitiveObject
	 *
	 * Constraint:
	 *     (type=Types name=ID (primitiveProperties+=PrimitiveProperties primitiveProperties+=PrimitiveProperties*)?)
	 */
	protected void sequence_PrimitiveObject(ISerializationContext context, PrimitiveObject semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PrimitiveProperties returns PrimitiveProperties
	 *
	 * Constraint:
	 *     stringFormat=FormatTypes
	 */
	protected void sequence_PrimitiveProperties(ISerializationContext context, PrimitiveProperties semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JSchemaPackage.Literals.PRIMITIVE_PROPERTIES__STRING_FORMAT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JSchemaPackage.Literals.PRIMITIVE_PROPERTIES__STRING_FORMAT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPrimitivePropertiesAccess().getStringFormatFormatTypesEnumRuleCall_2_1_0(), semanticObject.getStringFormat());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Property returns Property
	 *
	 * Constraint:
	 *     (type=Types name=ID)
	 */
	protected void sequence_Property(ISerializationContext context, Property semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JSchemaPackage.Literals.PROPERTY__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JSchemaPackage.Literals.PROPERTY__TYPE));
			if (transientValues.isValueTransient(semanticObject, JSchemaPackage.Literals.PROPERTY__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JSchemaPackage.Literals.PROPERTY__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPropertyAccess().getTypeTypesParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getPropertyAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Types returns Array
	 *
	 * Constraint:
	 *     array=Array
	 */
	protected void sequence_Types(ISerializationContext context, Array semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JSchemaPackage.Literals.ARRAY__ARRAY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JSchemaPackage.Literals.ARRAY__ARRAY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTypesAccess().getArrayArrayParserRuleCall_1_1_0(), semanticObject.getArray());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Types returns STRING
	 *
	 * Constraint:
	 *     string=STRING
	 */
	protected void sequence_Types(ISerializationContext context, STRING semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JSchemaPackage.Literals.STRING__STRING) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JSchemaPackage.Literals.STRING__STRING));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTypesAccess().getStringSTRINGTerminalRuleCall_0_1_0(), semanticObject.getString());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Types returns Types
	 *
	 * Constraint:
	 *     number=Number
	 */
	protected void sequence_Types(ISerializationContext context, Types semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JSchemaPackage.Literals.TYPES__NUMBER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JSchemaPackage.Literals.TYPES__NUMBER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTypesAccess().getNumberNumberParserRuleCall_2_0(), semanticObject.getNumber());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     hasProperties returns hasProperties
	 *
	 * Constraint:
	 *     properties+=Property+
	 */
	protected void sequence_hasProperties(ISerializationContext context, hasProperties semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
