/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.jSchema.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.xtext.example.mydsl.jSchema.Includes;
import org.xtext.example.mydsl.jSchema.JSchemaPackage;
import org.xtext.example.mydsl.jSchema.MainObject;
import org.xtext.example.mydsl.jSchema.PrimitiveObject;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Includes</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jSchema.impl.IncludesImpl#getIncludesMainObject <em>Includes Main Object</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jSchema.impl.IncludesImpl#getIncludesPrimitiveObject <em>Includes Primitive Object</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IncludesImpl extends MinimalEObjectImpl.Container implements Includes
{
  /**
   * The cached value of the '{@link #getIncludesMainObject() <em>Includes Main Object</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncludesMainObject()
   * @generated
   * @ordered
   */
  protected EList<MainObject> includesMainObject;

  /**
   * The cached value of the '{@link #getIncludesPrimitiveObject() <em>Includes Primitive Object</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncludesPrimitiveObject()
   * @generated
   * @ordered
   */
  protected EList<PrimitiveObject> includesPrimitiveObject;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IncludesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JSchemaPackage.Literals.INCLUDES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MainObject> getIncludesMainObject()
  {
    if (includesMainObject == null)
    {
      includesMainObject = new EObjectResolvingEList<MainObject>(MainObject.class, this, JSchemaPackage.INCLUDES__INCLUDES_MAIN_OBJECT);
    }
    return includesMainObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PrimitiveObject> getIncludesPrimitiveObject()
  {
    if (includesPrimitiveObject == null)
    {
      includesPrimitiveObject = new EObjectResolvingEList<PrimitiveObject>(PrimitiveObject.class, this, JSchemaPackage.INCLUDES__INCLUDES_PRIMITIVE_OBJECT);
    }
    return includesPrimitiveObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JSchemaPackage.INCLUDES__INCLUDES_MAIN_OBJECT:
        return getIncludesMainObject();
      case JSchemaPackage.INCLUDES__INCLUDES_PRIMITIVE_OBJECT:
        return getIncludesPrimitiveObject();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JSchemaPackage.INCLUDES__INCLUDES_MAIN_OBJECT:
        getIncludesMainObject().clear();
        getIncludesMainObject().addAll((Collection<? extends MainObject>)newValue);
        return;
      case JSchemaPackage.INCLUDES__INCLUDES_PRIMITIVE_OBJECT:
        getIncludesPrimitiveObject().clear();
        getIncludesPrimitiveObject().addAll((Collection<? extends PrimitiveObject>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JSchemaPackage.INCLUDES__INCLUDES_MAIN_OBJECT:
        getIncludesMainObject().clear();
        return;
      case JSchemaPackage.INCLUDES__INCLUDES_PRIMITIVE_OBJECT:
        getIncludesPrimitiveObject().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JSchemaPackage.INCLUDES__INCLUDES_MAIN_OBJECT:
        return includesMainObject != null && !includesMainObject.isEmpty();
      case JSchemaPackage.INCLUDES__INCLUDES_PRIMITIVE_OBJECT:
        return includesPrimitiveObject != null && !includesPrimitiveObject.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //IncludesImpl
