/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.jSchema.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.jSchema.JSchemaPackage;
import org.xtext.example.mydsl.jSchema.ObjectRequireMinimumProperties;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Object Require Minimum Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ObjectRequireMinimumPropertiesImpl extends ObjectImpl implements ObjectRequireMinimumProperties
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ObjectRequireMinimumPropertiesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JSchemaPackage.Literals.OBJECT_REQUIRE_MINIMUM_PROPERTIES;
  }

} //ObjectRequireMinimumPropertiesImpl
