/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.jSchema.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.jSchema.FormatTypes;
import org.xtext.example.mydsl.jSchema.JSchemaPackage;
import org.xtext.example.mydsl.jSchema.PrimitiveProperties;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Primitive Properties</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jSchema.impl.PrimitivePropertiesImpl#getStringFormat <em>String Format</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PrimitivePropertiesImpl extends MinimalEObjectImpl.Container implements PrimitiveProperties
{
  /**
   * The default value of the '{@link #getStringFormat() <em>String Format</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStringFormat()
   * @generated
   * @ordered
   */
  protected static final FormatTypes STRING_FORMAT_EDEFAULT = FormatTypes.DATE_TIME;

  /**
   * The cached value of the '{@link #getStringFormat() <em>String Format</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStringFormat()
   * @generated
   * @ordered
   */
  protected FormatTypes stringFormat = STRING_FORMAT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrimitivePropertiesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JSchemaPackage.Literals.PRIMITIVE_PROPERTIES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FormatTypes getStringFormat()
  {
    return stringFormat;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStringFormat(FormatTypes newStringFormat)
  {
    FormatTypes oldStringFormat = stringFormat;
    stringFormat = newStringFormat == null ? STRING_FORMAT_EDEFAULT : newStringFormat;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JSchemaPackage.PRIMITIVE_PROPERTIES__STRING_FORMAT, oldStringFormat, stringFormat));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JSchemaPackage.PRIMITIVE_PROPERTIES__STRING_FORMAT:
        return getStringFormat();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JSchemaPackage.PRIMITIVE_PROPERTIES__STRING_FORMAT:
        setStringFormat((FormatTypes)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JSchemaPackage.PRIMITIVE_PROPERTIES__STRING_FORMAT:
        setStringFormat(STRING_FORMAT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JSchemaPackage.PRIMITIVE_PROPERTIES__STRING_FORMAT:
        return stringFormat != STRING_FORMAT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (stringFormat: ");
    result.append(stringFormat);
    result.append(')');
    return result.toString();
  }

} //PrimitivePropertiesImpl
