/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.jSchema.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.jSchema.JSchemaPackage;
import org.xtext.example.mydsl.jSchema.STRING;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>STRING</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class STRINGImpl extends TypesImpl implements STRING
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected STRINGImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JSchemaPackage.Literals.STRING;
  }

} //STRINGImpl
