/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.generator;

import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import com.google.common.collect.Iterators;
import java.util.ArrayList;
import javax.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.mydsl.generator.ObjectClass;
import org.xtext.example.mydsl.generator.PrimitiveObjectClass;
import org.xtext.example.mydsl.jSchema.Includes;
import org.xtext.example.mydsl.jSchema.IsRoot;
import org.xtext.example.mydsl.jSchema.MainObject;
import org.xtext.example.mydsl.jSchema.Model;
import org.xtext.example.mydsl.jSchema.PrimitiveObject;
import org.xtext.example.mydsl.jSchema.hasProperties;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class JSchemaGenerator extends AbstractGenerator {
  @Inject
  @Extension
  private IQualifiedNameProvider _iQualifiedNameProvider;
  
  private ArrayList<PrimitiveObject> primitiveObjectList;
  
  private ArrayList<MainObject> mainObjectList;
  
  private ArrayList<ObjectClass> compiledMainObjects;
  
  private ArrayList<PrimitiveObjectClass> compiledPrimitiveObjects;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    ArrayList<PrimitiveObject> _arrayList = new ArrayList<PrimitiveObject>();
    this.primitiveObjectList = _arrayList;
    ArrayList<MainObject> _arrayList_1 = new ArrayList<MainObject>();
    this.mainObjectList = _arrayList_1;
    ArrayList<PrimitiveObjectClass> _arrayList_2 = new ArrayList<PrimitiveObjectClass>();
    this.compiledPrimitiveObjects = _arrayList_2;
    ArrayList<ObjectClass> _arrayList_3 = new ArrayList<ObjectClass>();
    this.compiledMainObjects = _arrayList_3;
    final Model abstractObjects = Iterators.<Model>filter(resource.getAllContents(), Model.class).next();
    int _size = this.primitiveObjectList.size();
    String _plus = ("Amount of primitive objects found: " + Integer.valueOf(_size));
    System.out.println(_plus);
    Iterable<PrimitiveObject> _filter = Iterables.<PrimitiveObject>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), PrimitiveObject.class);
    for (final PrimitiveObject primObj : _filter) {
      this.compiledPrimitiveObjects.add(this.compilePrimitiveObject(primObj));
    }
    Iterable<MainObject> _filter_1 = Iterables.<MainObject>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), MainObject.class);
    for (final MainObject obj : _filter_1) {
      {
        String bool = "false";
        String rootBool = "false";
        boolean _checkIfObjectContainsOtherObjects = this.checkIfObjectContainsOtherObjects(obj);
        boolean _equals = (_checkIfObjectContainsOtherObjects == true);
        if (_equals) {
          bool = "true";
        }
        IsRoot _root = obj.getRoot();
        boolean _notEquals = (!Objects.equal(_root, null));
        if (_notEquals) {
          rootBool = "true";
        }
        String _string = obj.getObjectName().toString();
        String _plus_1 = ((("Contains other objects: " + bool) + "  ") + _string);
        String _plus_2 = (_plus_1 + " PropertyListSize= ");
        int _size_1 = this.getProperties(obj).size();
        String _plus_3 = (_plus_2 + Integer.valueOf(_size_1));
        String _plus_4 = (_plus_3 + " isRoot: ");
        String _plus_5 = (_plus_4 + rootBool);
        System.out.println(_plus_5);
        this.compiledMainObjects.add(this.compileMainObject(obj));
      }
    }
    for (final ObjectClass compiledObject : this.compiledMainObjects) {
      if ((compiledObject.isRoot == true)) {
        System.out.println(compiledObject.getObjectJSchemaString());
      }
    }
  }
  
  public ObjectClass compileMainObject(final MainObject obj) {
    boolean isRoot = false;
    IsRoot _root = obj.getRoot();
    boolean _tripleNotEquals = (_root != null);
    if (_tripleNotEquals) {
      isRoot = true;
    }
    String _objectName = obj.getObjectName();
    final ObjectClass tempObject = new ObjectClass(_objectName, isRoot, obj);
    boolean _checkIfObjectContainsOtherObjects = this.checkIfObjectContainsOtherObjects(obj);
    boolean _equals = (_checkIfObjectContainsOtherObjects == true);
    if (_equals) {
      final ArrayList<String> includeNameList = new ArrayList<String>();
      Includes _includeObjects = obj.getIncludeObjects();
      boolean _tripleNotEquals_1 = (_includeObjects != null);
      if (_tripleNotEquals_1) {
        EList<String> _objectID = obj.getIncludeObjects().getObjectID();
        for (final String str : _objectID) {
          includeNameList.add(str);
        }
      }
      for (final String includedName : includeNameList) {
        {
          for (final MainObject mainObj : this.mainObjectList) {
            String _string = mainObj.getObjectName().toString();
            boolean _equals_1 = Objects.equal(_string, includedName);
            if (_equals_1) {
              tempObject.addMainObject(this.compileMainObject(mainObj));
            }
          }
          for (final PrimitiveObjectClass compPrimObj : this.compiledPrimitiveObjects) {
            boolean _notEquals = (!Objects.equal(compPrimObj.name, null));
            if (_notEquals) {
              boolean _equals_2 = Objects.equal(compPrimObj.name, includedName);
              if (_equals_2) {
                tempObject.addPrimitiveObject(compPrimObj);
              }
            }
          }
        }
      }
      ArrayList<hasProperties> _properties = this.getProperties(obj);
      for (final hasProperties e : _properties) {
        PrimitiveObject _propPrim = e.getProperties().getPropPrim();
        boolean _tripleNotEquals_2 = (_propPrim != null);
        if (_tripleNotEquals_2) {
          System.out.println("hasProperties = nested Primitive Object");
          tempObject.addHasPrimObj(this.compilePrimitiveObject(e.getProperties().getPropPrim()));
        } else {
          MainObject _propObj = e.getProperties().getPropObj();
          boolean _tripleNotEquals_3 = (_propObj != null);
          if (_tripleNotEquals_3) {
            System.out.println("hasProperties = nested Main Object");
            tempObject.addHasMainObj(this.compileMainObject(e.getProperties().getPropObj()));
          }
        }
      }
    }
    return tempObject;
  }
  
  public PrimitiveObjectClass compilePrimitiveObject(final PrimitiveObject obj) {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from ArrayList<Object> to PrimitiveProperties");
  }
  
  public boolean checkIfObjectContainsOtherObjects(final MainObject obj) {
    if (((obj.getIncludeObjects() != null) || (obj.getProperties() != null))) {
      return true;
    } else {
      return false;
    }
  }
  
  public ArrayList<hasProperties> getProperties(final MainObject obj) {
    final ArrayList<hasProperties> propertyList = new ArrayList<hasProperties>();
    EList<hasProperties> _properties = obj.getProperties();
    for (final hasProperties e : _properties) {
      propertyList.add(e);
    }
    return propertyList;
  }
  
  public Object stringBuilder(final String string) {
    return null;
  }
}
