/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.jSchema;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jSchema.Array#getArrayName <em>Array Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jSchema.Array#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jSchema.Array#getArrayType <em>Array Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getArray()
 * @model
 * @generated
 */
public interface Array extends EObject
{
  /**
   * Returns the value of the '<em><b>Array Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array Name</em>' attribute.
   * @see #setArrayName(String)
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getArray_ArrayName()
   * @model
   * @generated
   */
  String getArrayName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jSchema.Array#getArrayName <em>Array Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array Name</em>' attribute.
   * @see #getArrayName()
   * @generated
   */
  void setArrayName(String value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.jSchema.Property}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getArray_Properties()
   * @model containment="true"
   * @generated
   */
  EList<Property> getProperties();

  /**
   * Returns the value of the '<em><b>Array Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array Type</em>' attribute.
   * @see #setArrayType(String)
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getArray_ArrayType()
   * @model
   * @generated
   */
  String getArrayType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jSchema.Array#getArrayType <em>Array Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array Type</em>' attribute.
   * @see #getArrayType()
   * @generated
   */
  void setArrayType(String value);

} // Array
