/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.jSchema;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getBoolean()
 * @model
 * @generated
 */
public interface Boolean extends Types
{
} // Boolean
