/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.jSchema;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Includes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jSchema.Includes#getObjectID <em>Object ID</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getIncludes()
 * @model
 * @generated
 */
public interface Includes extends EObject
{
  /**
   * Returns the value of the '<em><b>Object ID</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object ID</em>' attribute list.
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getIncludes_ObjectID()
   * @model unique="false"
   * @generated
   */
  EList<String> getObjectID();

} // Includes
