/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.jSchema;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.jSchema.JSchemaFactory
 * @model kind="package"
 * @generated
 */
public interface JSchemaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "jSchema";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/JSchema";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "jSchema";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JSchemaPackage eINSTANCE = org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.jSchema.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.jSchema.impl.ModelImpl
   * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.jSchema.impl.ObjectImpl <em>Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.jSchema.impl.ObjectImpl
   * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getObject()
   * @generated
   */
  int OBJECT = 2;

  /**
   * The number of structural features of the '<em>Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_FEATURE_COUNT = MODEL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.jSchema.impl.ObjectRequireMinimumPropertiesImpl <em>Object Require Minimum Properties</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.jSchema.impl.ObjectRequireMinimumPropertiesImpl
   * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getObjectRequireMinimumProperties()
   * @generated
   */
  int OBJECT_REQUIRE_MINIMUM_PROPERTIES = 3;

  /**
   * The number of structural features of the '<em>Object Require Minimum Properties</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_REQUIRE_MINIMUM_PROPERTIES_FEATURE_COUNT = OBJECT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.jSchema.impl.NumberImpl <em>Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.jSchema.impl.NumberImpl
   * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getNumber()
   * @generated
   */
  int NUMBER = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__VALUE = OBJECT_REQUIRE_MINIMUM_PROPERTIES_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__PROPERTIES = OBJECT_REQUIRE_MINIMUM_PROPERTIES_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_FEATURE_COUNT = OBJECT_REQUIRE_MINIMUM_PROPERTIES_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.jSchema.impl.TypesImpl <em>Types</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.jSchema.impl.TypesImpl
   * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getTypes()
   * @generated
   */
  int TYPES = 4;

  /**
   * The number of structural features of the '<em>Types</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPES_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.jSchema.impl.PropertiesImpl <em>Properties</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.jSchema.impl.PropertiesImpl
   * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getProperties()
   * @generated
   */
  int PROPERTIES = 5;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTIES__PROPERTIES = 0;

  /**
   * The number of structural features of the '<em>Properties</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTIES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.jSchema.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.jSchema.impl.PropertyImpl
   * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__TYPE = 1;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.jSchema.impl.ArrayImpl <em>Array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.jSchema.impl.ArrayImpl
   * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getArray()
   * @generated
   */
  int ARRAY = 7;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY__ARRAY = TYPES_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY__LENGTH = TYPES_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_FEATURE_COUNT = TYPES_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.jSchema.impl.STRINGImpl <em>STRING</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.jSchema.impl.STRINGImpl
   * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getSTRING()
   * @generated
   */
  int STRING = 8;

  /**
   * The number of structural features of the '<em>STRING</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_FEATURE_COUNT = TYPES_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.jSchema.impl.BooleanImpl <em>Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.jSchema.impl.BooleanImpl
   * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 9;

  /**
   * The number of structural features of the '<em>Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FEATURE_COUNT = TYPES_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.jSchema.impl.NullImpl <em>Null</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.jSchema.impl.NullImpl
   * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getNull()
   * @generated
   */
  int NULL = 10;

  /**
   * The number of structural features of the '<em>Null</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NULL_FEATURE_COUNT = TYPES_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.jSchema.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.jSchema.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.jSchema.Number <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number</em>'.
   * @see org.xtext.example.mydsl.jSchema.Number
   * @generated
   */
  EClass getNumber();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.jSchema.Number#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.jSchema.Number#getValue()
   * @see #getNumber()
   * @generated
   */
  EAttribute getNumber_Value();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.jSchema.Number#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Properties</em>'.
   * @see org.xtext.example.mydsl.jSchema.Number#getProperties()
   * @see #getNumber()
   * @generated
   */
  EReference getNumber_Properties();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.jSchema.Object <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object</em>'.
   * @see org.xtext.example.mydsl.jSchema.Object
   * @generated
   */
  EClass getObject();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.jSchema.ObjectRequireMinimumProperties <em>Object Require Minimum Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Require Minimum Properties</em>'.
   * @see org.xtext.example.mydsl.jSchema.ObjectRequireMinimumProperties
   * @generated
   */
  EClass getObjectRequireMinimumProperties();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.jSchema.Types <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Types</em>'.
   * @see org.xtext.example.mydsl.jSchema.Types
   * @generated
   */
  EClass getTypes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.jSchema.Properties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Properties</em>'.
   * @see org.xtext.example.mydsl.jSchema.Properties
   * @generated
   */
  EClass getProperties();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.jSchema.Properties#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see org.xtext.example.mydsl.jSchema.Properties#getProperties()
   * @see #getProperties()
   * @generated
   */
  EReference getProperties_Properties();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.jSchema.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see org.xtext.example.mydsl.jSchema.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.jSchema.Property#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.jSchema.Property#getName()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.jSchema.Property#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.example.mydsl.jSchema.Property#getType()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.jSchema.Array <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array</em>'.
   * @see org.xtext.example.mydsl.jSchema.Array
   * @generated
   */
  EClass getArray();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.jSchema.Array#isArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see org.xtext.example.mydsl.jSchema.Array#isArray()
   * @see #getArray()
   * @generated
   */
  EAttribute getArray_Array();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.jSchema.Array#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see org.xtext.example.mydsl.jSchema.Array#getLength()
   * @see #getArray()
   * @generated
   */
  EAttribute getArray_Length();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.jSchema.STRING <em>STRING</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>STRING</em>'.
   * @see org.xtext.example.mydsl.jSchema.STRING
   * @generated
   */
  EClass getSTRING();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.jSchema.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean</em>'.
   * @see org.xtext.example.mydsl.jSchema.Boolean
   * @generated
   */
  EClass getBoolean();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.jSchema.Null <em>Null</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Null</em>'.
   * @see org.xtext.example.mydsl.jSchema.Null
   * @generated
   */
  EClass getNull();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JSchemaFactory getJSchemaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.jSchema.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.jSchema.impl.ModelImpl
     * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.jSchema.impl.NumberImpl <em>Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.jSchema.impl.NumberImpl
     * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getNumber()
     * @generated
     */
    EClass NUMBER = eINSTANCE.getNumber();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER__VALUE = eINSTANCE.getNumber_Value();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUMBER__PROPERTIES = eINSTANCE.getNumber_Properties();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.jSchema.impl.ObjectImpl <em>Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.jSchema.impl.ObjectImpl
     * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getObject()
     * @generated
     */
    EClass OBJECT = eINSTANCE.getObject();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.jSchema.impl.ObjectRequireMinimumPropertiesImpl <em>Object Require Minimum Properties</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.jSchema.impl.ObjectRequireMinimumPropertiesImpl
     * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getObjectRequireMinimumProperties()
     * @generated
     */
    EClass OBJECT_REQUIRE_MINIMUM_PROPERTIES = eINSTANCE.getObjectRequireMinimumProperties();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.jSchema.impl.TypesImpl <em>Types</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.jSchema.impl.TypesImpl
     * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getTypes()
     * @generated
     */
    EClass TYPES = eINSTANCE.getTypes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.jSchema.impl.PropertiesImpl <em>Properties</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.jSchema.impl.PropertiesImpl
     * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getProperties()
     * @generated
     */
    EClass PROPERTIES = eINSTANCE.getProperties();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTIES__PROPERTIES = eINSTANCE.getProperties_Properties();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.jSchema.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.jSchema.impl.PropertyImpl
     * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__NAME = eINSTANCE.getProperty_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__TYPE = eINSTANCE.getProperty_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.jSchema.impl.ArrayImpl <em>Array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.jSchema.impl.ArrayImpl
     * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getArray()
     * @generated
     */
    EClass ARRAY = eINSTANCE.getArray();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARRAY__ARRAY = eINSTANCE.getArray_Array();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARRAY__LENGTH = eINSTANCE.getArray_Length();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.jSchema.impl.STRINGImpl <em>STRING</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.jSchema.impl.STRINGImpl
     * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getSTRING()
     * @generated
     */
    EClass STRING = eINSTANCE.getSTRING();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.jSchema.impl.BooleanImpl <em>Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.jSchema.impl.BooleanImpl
     * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getBoolean()
     * @generated
     */
    EClass BOOLEAN = eINSTANCE.getBoolean();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.jSchema.impl.NullImpl <em>Null</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.jSchema.impl.NullImpl
     * @see org.xtext.example.mydsl.jSchema.impl.JSchemaPackageImpl#getNull()
     * @generated
     */
    EClass NULL = eINSTANCE.getNull();

  }

} //JSchemaPackage
