/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.jSchema;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jSchema.MainObject#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jSchema.MainObject#getRoot <em>Root</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jSchema.MainObject#getInherits <em>Inherits</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jSchema.MainObject#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getMainObject()
 * @model
 * @generated
 */
public interface MainObject extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getMainObject_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jSchema.MainObject#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Root</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Root</em>' containment reference.
   * @see #setRoot(IsRoot)
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getMainObject_Root()
   * @model containment="true"
   * @generated
   */
  IsRoot getRoot();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jSchema.MainObject#getRoot <em>Root</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Root</em>' containment reference.
   * @see #getRoot()
   * @generated
   */
  void setRoot(IsRoot value);

  /**
   * Returns the value of the '<em><b>Inherits</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inherits</em>' containment reference list.
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getMainObject_Inherits()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getInherits();

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.jSchema.AbstractObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getMainObject_Properties()
   * @model containment="true"
   * @generated
   */
  EList<AbstractObject> getProperties();

} // MainObject
