/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.jSchema;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jSchema.Model#getAbstractObject <em>Abstract Object</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Abstract Object</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.jSchema.AbstractObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abstract Object</em>' containment reference list.
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getModel_AbstractObject()
   * @model containment="true"
   * @generated
   */
  EList<AbstractObject> getAbstractObject();

} // Model
