/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.jSchema;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jSchema.Object#getObjectName <em>Object Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jSchema.Object#getIncludeObjects <em>Include Objects</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jSchema.Object#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getObject()
 * @model
 * @generated
 */
public interface Object extends AbstractObject
{
  /**
   * Returns the value of the '<em><b>Object Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object Name</em>' attribute.
   * @see #setObjectName(String)
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getObject_ObjectName()
   * @model
   * @generated
   */
  String getObjectName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jSchema.Object#getObjectName <em>Object Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object Name</em>' attribute.
   * @see #getObjectName()
   * @generated
   */
  void setObjectName(String value);

  /**
   * Returns the value of the '<em><b>Include Objects</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Include Objects</em>' containment reference.
   * @see #setIncludeObjects(Includes)
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getObject_IncludeObjects()
   * @model containment="true"
   * @generated
   */
  Includes getIncludeObjects();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jSchema.Object#getIncludeObjects <em>Include Objects</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Include Objects</em>' containment reference.
   * @see #getIncludeObjects()
   * @generated
   */
  void setIncludeObjects(Includes value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.jSchema.hasProperties}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getObject_Properties()
   * @model containment="true"
   * @generated
   */
  EList<hasProperties> getProperties();

} // Object
