/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.jSchema;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primitive Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jSchema.PrimitiveObject#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jSchema.PrimitiveObject#getPrimitiveProperties <em>Primitive Properties</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getPrimitiveObject()
 * @model
 * @generated
 */
public interface PrimitiveObject extends AbstractObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(PrimitiveTypes)
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getPrimitiveObject_Type()
   * @model containment="true"
   * @generated
   */
  PrimitiveTypes getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jSchema.PrimitiveObject#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(PrimitiveTypes value);

  /**
   * Returns the value of the '<em><b>Primitive Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.jSchema.PrimitiveProperties}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primitive Properties</em>' containment reference list.
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getPrimitiveObject_PrimitiveProperties()
   * @model containment="true"
   * @generated
   */
  EList<PrimitiveProperties> getPrimitiveProperties();

} // PrimitiveObject
