/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.jSchema;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jSchema.Property#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jSchema.Property#getObject <em>Object</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(PrimitiveTypes)
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getProperty_Type()
   * @model containment="true"
   * @generated
   */
  PrimitiveTypes getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jSchema.Property#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(PrimitiveTypes value);

  /**
   * Returns the value of the '<em><b>Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object</em>' containment reference.
   * @see #setObject(MainObject)
   * @see org.xtext.example.mydsl.jSchema.JSchemaPackage#getProperty_Object()
   * @model containment="true"
   * @generated
   */
  MainObject getObject();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jSchema.Property#getObject <em>Object</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object</em>' containment reference.
   * @see #getObject()
   * @generated
   */
  void setObject(MainObject value);

} // Property
